Add `getPronouns` method for mod integration
ashhhleyyy/player-pronouns pull request #9
Opened 2022-08-17 09:07 UTC by sisby-folk

Just adds a simple static `@Nullable Pronouns getPronouns(player)` method for other mods to use.

2022-08-17 10:29 UTC, ashhhleyyy requested changes
I'll look at getting proper maven publishing setup for this, and I'll probably work on a full API interface for a `2.0.0` release at some point

2022-08-17 10:29 UTC, ashhhleyyy commented on src/main/java/io/github/ashisbored/playerpronouns/PlayerPronouns.java
> +    public static @Nullable Pronouns getPronouns(ServerPlayerEntity player) {
It's probably worth exposing a second version of this which takes a UUID directly too

2022-08-17 10:29 UTC, ashhhleyyy commented on build.gradle.kts
> +version = "1.5.1+1.19"
Nit: this version bump should be to `1.6.0` because its a new 'feature' rather than just a bugfix

2022-08-20 06:14 UTC, sisby-folk reviewed
Sorted these two out. Let me know if there's anything else you'd like to tweak.

2022-08-20 10:47 UTC, ashhhleyyy approved these changes

2022-08-20 10:48 UTC, merged